# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  languageName: English
  weight: 1
zh:
  languageCode: zh-Hans
  languageName: 中文
  title: 李梓民
  weight: 2
  params:
    description: 李梓民，中南大学物理学院副教授，研究方向包括量子光学、开放量子系统、非厄米物理和量子计算。
    marketing:
      seo:
        description: 李梓民，中南大学物理学院副教授、硕士生导师，研究量子光学、开放量子系统、非厄米物理和量子计算。
    locale:
      date_format: '2006年1月2日'
      time_format: '15:04'
      address_format: zh
    footer:
      copyright:
        notice: '© {year} 李梓民 · {license}'
  menu:
    main:
    - name: 首页
      url: "#about"
      weight: 10
    - name: 文章
      url: "#posts"
      weight: 20
    - name: 研究兴趣
      url: "#projects"
      weight: 50
    - name: 团队
      url: "#team"
      weight: 40
    - name: 论文
      url: "#featured"
      weight: 30
    - name: 联系
      url: "#contact"
      weight: 70
    - name: 相册
      url: "#gallery"
      weight: 65
    - name: 课程
      identifier: courses
      url: "/#courses"
      weight: 60
    - name: 大学物理
      parent: courses
      url: "/course/university-physics/"
      weight: 20
    - name: 量子光学
      parent: courses
      url: "https://zimin.li/quantum-optics/"
      weight: 30
